question_data = [
    {"texto": "La sangre de una babosa es verde", "respuesta": "Verdadero"},
    {"texto": "El animal más ruidoso es el elefante africano.", "respuesta": "Falso"},
    {"texto": "Aproximadamente una cuarta parte de los huesos humanos están en los pies.", "respuesta": "Verdadero"},
    {"texto": "La superficie total de un pulmón humano es del tamaño de un campo de fútbol.", "respuesta": "Verdadero"},
    {"texto": "En West Virginia, EE. UU., si atropellas accidentalmente a un animal con tu automóvil "
              "puedes llevártelo a casa para comer", "respuesta": "Verdadero"},
    {"texto": "En Londres, Reino Unido, si mueres en la Casa del Parlamento, tienes"
              "derecho a un funeral de Estado", "respuesta": "Falso"},
    {"texto": "Es ilegal orinar en el océano en Portugal", "respuesta": "Verdadero"},
    {"texto": "Puedes llevar a una vaca escaleras abajo, pero no subirlas", "respuesta": "Falso"},
    {"texto": "Google se llamaba originalmente 'Backrub'.", "respuesta": "Verdadero"},
    {"texto": "El apellido de soltera de la madre de Buzz Aldrin era 'Moon'.", "respuesta": "Verdadero"},
    {"texto": "Ningún trozo de papel seco cuadrado se puede doblar por la mitad más de 7 veces.", "respuesta": "Falso"},
    {"texto": "Unas pocas onzas de lata de chocolate para matar a un perro pequeño", "respuesta": "Verdadero"}
]

data_2 = [
    {"category": "Entretenimiento: película",
     "tipo": "booleano",
     "dificultad": "fácil",
     "pregunta": "El copiloto y mejor amigo de Han Solo, Chewbacca, es un Ewok",
     "respuesta": "Falso",
     "incorrectas_respuestas": ["Verdadero"]},
    {"category": "Entretenimiento: película",
     "tipo": "booleano",
     "dificultad": "fácil",
     "pregunta": "Leonardo DiCaprio ganó un Oscar al Mejor Actor en El Aviador de 2004.",
     "respuesta": "Falso",
     "incorrectas_respuestas": ["Verdadero"]},
    {"category": "Entretenimiento: película",
     "tipo": "booleano", "dificultad": "fácil",
     "pregunta": "La película 2001: A Space Odyssey; fue estrenada el 31 de diciembre de 2000.",
     "respuesta": "Falso",
     "incorrectas_respuestas": ["Verdadero"]},
    {"category": "Entretenimiento: película",
     "tipo": "booleano",
     "dificultad": "fácil",
     "pregunta": "Matt Damon interpretó a un astronauta varado en un planeta extraterrestre en ambas películas"
                 " Interestelar y el marciano",
     "respuesta": "Verdadero",
     "incorrectas_respuestas": ["Falso"]},
    {"category": "Entretenimiento: película",
     "tipo": "booleano",
     "dificultad": "fácil",
     "pregunta": "Shaquille O'Neal apareció en la película Space Jam de 1997",
     "respuesta": "Falso",
     "incorrectas_respuestas": ["Verdadero"]},
    {"category": "Entretenimiento: película",
     "tipo": "booleano",
     "dificultad": "fácil",
     "pregunta": "Samuel L. Jackson tenía las palabras, Bad Motherf*cker; escritas en su sable de luz"
                 "durante el rodaje de Star Wars.",
     "respuesta": "Verdadero",
     "incorrectas_respuestas": ["Falso"]},
    {"category": "Entretenimiento: película",
     "tipo": "booleano",
     "dificultad": "fácil",
     "pregunta": "En la trilogía original de Star Wars, "
                 "David Prowse era el actor que interpretó físicamente a Darth Vader",
     "respuesta": "Verdadero",
     "incorrectas_respuestas": ["Falso"]},
    {"category": "Entretenimiento: película",
     "tipo": "booleano",
     "dificultad": "fácil",
     "pregunta": "En la trilogía original de Star Wars, Alec Guinness proporcionó la voz de Darth Vader.",
     "respuesta": "Falso",
     "incorrectas_respuestas": ["Verdadero"]},
    {"category": "Entretenimiento: película",
     "tipo": "booleano",
     "dificultad": "fácil",
     "pregunta": "Minions; fue lanzada el 10 de junio de 2015.",
     "respuesta": "Falso",
     "incorrectas_respuestas": ["Verdadero"]},
    {"category": "Entretenimiento: película",
     "tipo": "booleano",
     "dificultad": "fácil",
     "pregunta": "El actor Tommy Chong cumplió condena en prisión",
     "respuesta": "Verdadero",
     "incorrectas_respuestas": ["Falso"]}
]
